# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        # prevents giant files from being committed
      - id: check-yaml
        # checks yaml files for parseable syntax
      - id: requirements-txt-fixer
        # sorts entries in requirements.txt
      - id: trailing-whitespace
        # trims trailing whitespace
      - id: end-of-file-fixer
        # ensures that a file is either empty, or ends with one newline
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        # Removes unused imports and unused variables as reported by pyflakes
        args: [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
          ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        # A Python utility/ library to sort imports.
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        # Python code formatter (with Jupyter Notebook support)
        args: ["--quiet"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.2.0"
  #   hooks:
  #     - id: mypy
  #       # static typing for Python
